server:
  port: 9999
spring:
  application:
    name: @project.name.deploy@
  profiles:
    active: @profile.name@
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bill
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.bill.server.dao.entity
  mapper-locations: "classpath:mapper/**/*Mapper.xml"
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    cache-enabled: false
  global-config:
    banner: false
    db-config:
      id-type: auto
      workerId: ${workerId}
      datacenterId: ${datacenterId}
      capital-mode: true
      field-strategy: not_empty
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql

---
spring:
  profiles: dev
server:
  port: 8989

---
spring:
  profiles: test
server:
  port: 9090